import 'server-only'
import { cookies } from 'next/headers'
import { randomUUID, pbkdf2Sync, randomBytes, createHmac, timingSafeEqual } from 'crypto'
import { eq, sql } from 'drizzle-orm'
import { getDb } from '@/lib/db/connection'
import { user as userTable } from '@/lib/db/schema'
import { MASTER_ADMIN_EMAIL, getDefaultPermissions } from '@/lib/permissions'
import type { UserRole, AdminRank, Permission } from '@/lib/permissions'
export interface AuthUser{id:string;name:string;email:string;isAdmin:boolean;role:UserRole;rank?:AdminRank;title?:string;username?:string;phone?:string;showFullName:boolean;permissions:Permission[]}
function getSecret(){const s=process.env.AUTH_SECRET;if(!s){if(process.env.NODE_ENV!=='production')return createHmac('sha256','dev-fallback').update(process.cwd()).digest('hex');throw new Error('AUTH_SECRET is not configured')}return s}
function hashPassword(p:string){const salt=randomBytes(16),key=pbkdf2Sync(p,salt,100000,32,'sha256');return`${salt.toString('hex')}:${key.toString('hex')}`}
function verifyPassword(p:string,stored:string){try{const[s,k]=stored.split(':'),salt=Buffer.from(s,'hex'),key=pbkdf2Sync(p,salt,100000,32,'sha256'),expected=Buffer.from(k,'hex');return key.length===expected.length&&timingSafeEqual(key,expected)}catch{return false}}
function signToken(payload:Record<string,unknown>){const data=Buffer.from(JSON.stringify(payload)).toString('base64url'),sig=createHmac('sha256',getSecret()).update(data).digest('base64url');return`${data}.${sig}`}
function verifyToken(token:string){const p=token.split('.');if(p.length!==2)return null;const[data,sig]=p,expected=createHmac('sha256',getSecret()).update(data).digest('base64url'),a=Buffer.from(sig),b=Buffer.from(expected);if(a.length!==b.length||!timingSafeEqual(a,b))return null;try{return JSON.parse(Buffer.from(data,'base64url').toString()) as Record<string,unknown>}catch{return null}}
const normalizeEmail=(e:string)=>e.trim().toLowerCase();const serializePermissions=(p?:Permission[])=>JSON.stringify(Array.isArray(p)?p:[]);function parsePermissions(raw:unknown):Permission[]{if(Array.isArray(raw))return raw as Permission[];try{return typeof raw==='string'?JSON.parse(raw):[]}catch{return[]}}
function mapDbUser(u:any):AuthUser{const role=(u.role as UserRole)||(u.isAdmin?'master_admin':'user');return{id:u.id,name:u.name,email:u.email,isAdmin:u.isAdmin??false,role,rank:u.rank??undefined,title:u.title??undefined,username:u.username??undefined,phone:u.phone??undefined,showFullName:u.showFullName??false,permissions:parsePermissions(u.permissions)}}
export function validateEmail(e:string){if(!e||typeof e!=='string')return'Email is required';return/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e.trim())?null:'Invalid email format'}
export function validatePassword(p:string){if(!p)return'Password is required';if(p.length<8)return'Password must be at least 8 characters';if(p.length>128)return'Password must be at most 128 characters';return null}
export function validateName(n:string){if(!n||typeof n!=='string'||!n.trim())return'Name is required';if(n.trim().length>100)return'Name must be at most 100 characters';return null}
export async function createUser(name:string,email:string,password:string,isAdmin=false,role:UserRole='user',rank?:AdminRank,title?:string){const db=await getDb();if(!db)throw new Error('Database not available');const em=normalizeEmail(email);if((await db.select({id:userTable.id}).from(userTable).where(eq(userTable.email,em)).limit(1)).length)throw new Error('An account with this email already exists');const id=randomUUID();await db.insert(userTable).values({id,name:name.trim(),email:em,passwordHash:hashPassword(password),isAdmin,role,rank:rank??(isAdmin?(role==='master_admin'?'master':'junior'):undefined),title:title??(role==='master_admin'?'Master Admin':undefined),permissions:serializePermissions(getDefaultPermissions(role)),tokenVersion:0,accountStatus:'active',createdAt:new Date(),updatedAt:new Date()});return{id,name:name.trim(),email:em}}
export async function authenticateUser(email:string,password:string){const db=await getDb();if(!db)return null;const rows=await db.select().from(userTable).where(eq(userTable.email,normalizeEmail(email))).limit(1);if(!rows.length||rows[0].accountStatus!=='active'||!rows[0].passwordHash||!verifyPassword(password,rows[0].passwordHash))return null;return mapDbUser(rows[0])}
export async function createSession(userId:string){const db=await getDb();if(!db)throw new Error('Database not available');const rows=await db.select().from(userTable).where(eq(userTable.id,userId)).limit(1);if(!rows.length||rows[0].accountStatus!=='active')throw new Error('User unavailable');const u=rows[0];return signToken({userId:u.id,tokenVersion:u.tokenVersion??0,exp:Date.now()+604800000})}
export async function getCurrentUser(){const token=(await cookies()).get('session')?.value;if(!token)return null;const payload=verifyToken(token);if(!payload||Number(payload.exp)<Date.now())return null;const db=await getDb();if(!db)return null;const rows=await db.select().from(userTable).where(eq(userTable.id,String(payload.userId))).limit(1);if(!rows.length)return null;const u=rows[0];if(u.accountStatus!=='active'||(u.tokenVersion??0)!==((payload.tokenVersion as number)??0))return null;return mapDbUser(u)}
export async function deleteSession(){}
export function generateResetToken(email:string){return signToken({type:'reset',email:normalizeEmail(email),exp:Date.now()+3600000})}export function verifyResetToken(t:string){const p=verifyToken(t);return p&&p.type==='reset'&&Number(p.exp)>=Date.now()?String(p.email):null}
export async function updatePassword(email:string,p:string){const db=await getDb();if(!db)return false;await db.update(userTable).set({passwordHash:hashPassword(p),tokenVersion:sql`${userTable.tokenVersion}+1`,updatedAt:new Date()}).where(eq(userTable.email,normalizeEmail(email)));return true}
export async function updateUser(id:string,u:{name?:string;email?:string;username?:string;phone?:string;showFullName?:boolean}){const db=await getDb();if(!db)return false;const s:any={updatedAt:new Date()};if(u.name)s.name=u.name.trim();if(u.email)s.email=normalizeEmail(u.email);if(u.username!==undefined)s.username=u.username||null;if(u.phone!==undefined)s.phone=u.phone||null;if(u.showFullName!==undefined)s.showFullName=u.showFullName;await db.update(userTable).set(s).where(eq(userTable.id,id));return true}
export function generateEmailVerificationToken(email:string){return signToken({type:'verify',email:normalizeEmail(email),exp:Date.now()+86400000})}export function verifyEmailToken(t:string){const p=verifyToken(t);return p&&p.type==='verify'&&Number(p.exp)>=Date.now()?String(p.email):null}
export async function markEmailVerified(email:string){const db=await getDb();if(!db)return false;await db.update(userTable).set({emailVerified:true,updatedAt:new Date()}).where(eq(userTable.email,normalizeEmail(email)));return true}export async function emailExists(email:string){const db=await getDb();if(!db)return false;return(await db.select({id:userTable.id}).from(userTable).where(eq(userTable.email,normalizeEmail(email))).limit(1)).length>0}export async function isEmailVerified(email:string){const db=await getDb();if(!db)return false;const r=await db.select({v:userTable.emailVerified}).from(userTable).where(eq(userTable.email,normalizeEmail(email))).limit(1);return r[0]?.v??false}
function getAdminEmail(){return process.env.ADMIN_EMAIL||MASTER_ADMIN_EMAIL}function getAdminPassword(){if(!process.env.ADMIN_PASSWORD)throw new Error('ADMIN_PASSWORD is required to seed the initial admin account');return process.env.ADMIN_PASSWORD}let _seedingDbAdmin=false
export async function seedDbAdmin(){if(_seedingDbAdmin)return;_seedingDbAdmin=true;try{const db=await getDb();if(!db)return;const email=normalizeEmail(getAdminEmail());if((await db.select({id:userTable.id}).from(userTable).where(eq(userTable.email,email)).limit(1)).length)return;await db.insert(userTable).values({id:randomUUID(),name:'Admin',email,passwordHash:hashPassword(getAdminPassword()),isAdmin:true,role:'master_admin',rank:'master',title:'Master Admin',permissions:serializePermissions(getDefaultPermissions('master_admin')),accountStatus:'active',tokenVersion:0,createdAt:new Date(),updatedAt:new Date()}).catch(()=>{})}finally{_seedingDbAdmin=false}}
export async function requireAdmin(){const u=await getCurrentUser();if(!u||!u.isAdmin)throw new Error('Unauthorized: admin access required');return u}export async function requireMasterAdmin(){const u=await getCurrentUser();if(!u||u.role!=='master_admin')throw new Error('Unauthorized: master admin access required');return u}export async function getAdminUser(){const u=await getCurrentUser();return u?.isAdmin?u:null}
export interface AdminUserListItem extends AuthUser{};export interface AdminUserUpdate{role?:UserRole;rank?:AdminRank;title?:string;permissions?:Permission[]}
export async function listAllUsers(){const db=await getDb();if(!db)return[];return(await db.select().from(userTable)).map(mapDbUser)}export async function getUserById(id:string){const db=await getDb();if(!db)return null;const r=await db.select().from(userTable).where(eq(userTable.id,id)).limit(1);return r.length?mapDbUser(r[0]):null}
export async function setUserAdmin(id:string,u:AdminUserUpdate){const db=await getDb();if(!db)throw new Error('Database not available');const s:any={updatedAt:new Date(),tokenVersion:sql`${userTable.tokenVersion}+1`};if(u.role!==undefined){s.role=u.role;s.isAdmin=u.role==='admin'||u.role==='master_admin'}if(u.rank!==undefined)s.rank=u.rank;if(u.title!==undefined)s.title=u.title||null;if(u.permissions!==undefined)s.permissions=serializePermissions(u.permissions);await db.update(userTable).set(s).where(eq(userTable.id,id));const x=await getUserById(id);if(!x)throw new Error('User not found');return x}
export async function demoteUserToRegular(id:string){await setUserAdmin(id,{role:'user',permissions:[]})}
